// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDViRlpzjkJF1AmI6ZCqs6JYOztIC_orWI',
    appId: '1:126967801988:web:1bd6d7bee6d9dfc8c3fad1',
    messagingSenderId: '126967801988',
    projectId: 'fir-example-f5c12',
    authDomain: 'fir-example-f5c12.firebaseapp.com',
    storageBucket: 'fir-example-f5c12.firebasestorage.app',
    measurementId: 'G-CVHT87X1G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqs_vRtSYQ0LcyOSuDIxWXCK1vzGku6hQ',
    appId: '1:126967801988:android:0c385899eecf70c0c3fad1',
    messagingSenderId: '126967801988',
    projectId: 'fir-example-f5c12',
    storageBucket: 'fir-example-f5c12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvEjOx245uqY3V40tZlYvJf4hINiNZmVM',
    appId: '1:126967801988:ios:6290deba5d0e6a4cc3fad1',
    messagingSenderId: '126967801988',
    projectId: 'fir-example-f5c12',
    storageBucket: 'fir-example-f5c12.firebasestorage.app',
    iosBundleId: 'com.baiomy.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvEjOx245uqY3V40tZlYvJf4hINiNZmVM',
    appId: '1:126967801988:ios:6290deba5d0e6a4cc3fad1',
    messagingSenderId: '126967801988',
    projectId: 'fir-example-f5c12',
    storageBucket: 'fir-example-f5c12.firebasestorage.app',
    iosBundleId: 'com.baiomy.firebaseExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDViRlpzjkJF1AmI6ZCqs6JYOztIC_orWI',
    appId: '1:126967801988:web:efeecab6e3804e60c3fad1',
    messagingSenderId: '126967801988',
    projectId: 'fir-example-f5c12',
    authDomain: 'fir-example-f5c12.firebaseapp.com',
    storageBucket: 'fir-example-f5c12.firebasestorage.app',
    measurementId: 'G-S96P842B8E',
  );
}
